blank_issues_enabled: false
contact_links:
  - name: codez.new related issues
    url: https://github.com/stackblitz/codez.new/issues/new/choose
    about: Report issues related to codez.new (not codez.diy)
  - name: Chat
    url: https://thinktank.ottomator.ai
    about: Ask questions and discuss with other codez.diy users.
